### PR TITLE
Static pages  #30

### PR DESCRIPTION
**Pull request by netman92**
Simple team page.

http://dev.pycon.cz/team.html

### CODE REVIEW

**Comment by thatdocslady** [comment]
The team info should be taken from here: https://gist.github.com/tricoder42/529b6c1cfd2bd6952fb6

Also, missing entry in top navbar

**Comment by thatdocslady** [comment]
Another idea: Convert name from plain text to twitter link, it's good for marketing/followers

**Comment by netman92** [comment]
@thatdocslady I've add team members, but I think, that text is not appropriate.
Also added CoC from markdown.

**Comment by thatdocslady** [comment]
I will fix the text on all sections as soon as you set up the structure, same for all the other page requests that are open. For now maybe we can keep this (and the Travel and other pages) off the navbar so that they're not linked from anywhere, and when we're ready to publish we can link them.

**Comment by netman92** [comment]
I will not **AGAIN** remove link from navbar. When this pages will be ready, I will publish it.

Currently we can add/edit content on coc and team page. I don't see the problem, why we should wait for another (just travel). We have to stop running in circles.

**Comment by netman92** [comment]
http://dev.pycon.cz/getting-here.html - base skeleton

**Comment by netman92** [comment]
http://dev.pycon.cz/sponsorship.html

**Comment by encukou** [comment]
Regarding content for greeing-here.html, I'll ask if we can just copy http://devconf.cz/transportation

**Comment by netman92** [comment]
:+1: ok

**Comment by encukou** [comment]
It's OK for us to copy from http://devconf.cz/transportation , though we should check if it's still current, and remove Devconf-specific stuff.
And we should be nice and credit them in the page's footer, if we use their content.

**Pull request merged**
