### PR TITLE
Summary e-mail proposal

### PR DESCRIPTION
**Pull request by honzajavorek**
Kick off. Needs more work - proofreading, etc.

cc @tricoder42 @dariathedaria

### CODE REVIEW

**Comment by calmrat** [comment]
Looks good; is there a form for submitting feedback available (to also support anonymous submission)? this seems preferable to making people sign into github. But... i'm not opposed either way. Just thinking...

**Comment by honzajavorek** [comment]
I don't know about form, but it's a good point. I thought people could just reply to the mail so the reaction would arrive to `info ... pycon.cz`, but I agree that it's not anonymous and it should be. We could create a simple Google Form with one text area or something.

**Comment by calmrat** [comment]
Another thought; if you want to incentivize folks sending feedback, maybe
there's something we could offer? Maybe a random raffle for three free
tickets to next year's event, for example... for all folks who submit by
DEADLINE.

**Comment by baradrb** [comment]
I will proofread it :)

**Comment by tricoder42** [comment]
@kejbaly2 I really want to make the form anonymous.

**Comment by calmrat** [comment]
+1 to that; just a note, it's possible to do both. For those who don't care
about anonymity and are happy to share their opinions and perspectives
transparently and want a chance to get something back for their
efforts/contributions (providing feedback is both of these things IMO),
they can add their name to a optional 'contact field' included in the form.

Anyway, nice work folks! Looking forward to kicking off discussions about
the SECOND ANNUAL PyCon CZ 2016! :)

-Chris

**Pull request merged**
