### PR TITLE
Initial content cleanup

### PR DESCRIPTION
**Pull request by thatdocslady**
- Fixed the text to refer to IL everywhere
- Edited team list (WIP)
- Hidden future content
- Added ti.to widget (PLZ TEST)

### CODE REVIEW

**Comment by thatdocslady** [comment]
OOOOOOPS! Wrong repo, not sure what happened here. Sorry @tricoder42 ! Will fix now.

**Comment by thatdocslady** [comment]
Closing PR and moving to correct repo.

**Comment by tricoder42** [comment]
No worries, I'm super excited that you've forked this repo! Good luck with PyCon IL!

**Comment by thatdocslady** [comment]
Thanks, and thanks for the MIT license, we added proper credit and hugs on
our website :)

**Comment by honzajavorek** [comment]
:heart: :+1:

**Pull request closed without merging**
