### PR TITLE
Update Sprints & Workshops

### PR DESCRIPTION
**Pull request by encukou**
- Replace Nischal's NLP workshop by Robert's Event-Sourced Domain Models
- Use Markdown in abstracts; link the mentioned projects
- Add workshop requirements
- Put social links after speaker names
- Mention other sprints
- Grammar fixes
- Rename "This is the end" to "Closing"
  (unlike Talks, this page is not organized chronologically, so we
  need to make it a bit clearer that this refers to the end of the
  conference)

### CODE REVIEW

**Comment by tricoder42** [comment]
This is awesome work, @encukou! I promote you to frontend developer :trophy: :+1: :smiley:

**Comment by honzajavorek** [comment]
Lol :-D we are spoiling this guy

**Comment by encukou** [comment]
Oh no! That's not really what I wanted .... :)

Anyway, can you please update the site? I'd like to tell Robert he's listed.

**Comment by tricoder42** [comment]
I've updated it yesterday, but we have issues with long caching. Please refresh the site now, it should be fixed today.

**Comment by encukou** [comment]
Nooe, even with `curl` it still gives me the old version :(

**Comment by tricoder42** [comment]
Fixed, sorry for that

**Pull request merged**
