### PR TITLE
Edited home and timeline text (and created dev branch for staging)

### PR DESCRIPTION
**Pull request by thatdocslady**

### CODE REVIEW

**Comment by honzajavorek** [comment]
:+1: looks great!

**Comment by thatdocslady** [comment]
@honzajavorek do you mean that you like the text, or that the files are sane and the PR can be merged? </troll>

**Comment by honzajavorek** [comment]
Basically, I'd merge it right away, but I don't know what's current merging policy here. I like the text and the files are sane.

**Comment by netman92** [comment]
I've fixed link and added target=_blank.

Merging policy we can discuss on slack.

**Pull request merged**
